spring:
  application:
    name: auth-service

  datasource:
    # URL corregida al nombre oficial: vetnova_auth
    url: jdbc:mysql://localhost:3306/vetnova_auth?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

server:
  port: 8081

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

logging:
  level:
    org:
      springframework:
        web: INFO
    com:
      vetnova: DEBUG

jwt:
  secret: vetnova_auth_secret_key_2026_segura_para_desarrollo
  expiration: 3600000