spring:
  application:
    name: usuarios

  datasource:
    url: jdbc:mysql://localhost:3306/vetnova_usuarios?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: '' 
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true # <-- Agregado: Espera a que se creen las tablas antes de cargar el SQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  sql:
    init:
      mode: always # <-- Agregado: Fuerza la ejecución de import.sql en bases de datos reales

server:
  port: 8082

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html