spring:
  application:
    name: ms-sucursales-administracion

  datasource:
    url: jdbc:mysql://localhost:3306/vetnova_sucursales?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true

server:
  port: 8090

notificaciones:
  url: http://localhost:8089/api/v1/notificaciones

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs

  swagger-ui:
    enabled: true
    path: /swagger-ui.html